export { default as Patient } from './Patient'
export { default as Doctor } from './Doctor'
export { default as Login } from './Login'
export { default as NotFound } from './NotFound'
export { default as Main } from './Main'
export { default as Register } from './Register'
